### ISSUE TITLE
Error when loading the libcompute_depth.so

### ISSUE THREAD

**Issue by 4bitadder** [cogaplex-bts/bts#11]
Hello

I used anaconda environment with tensorflow=1.14.0 (by conda install tensorflow-gpu=1.14.0), cuda10.0, and python 3.6.

The libcompute_depth.so can be compiled following the steps in readme. But when I try to load this library,  e.g.,

compute_depth_grad_module = tf.load_op_library('custom_layer/build/libcompute_depth.so')

It reports the following error

lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: custom_layer/build/libcompute_depth.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

Do you have any suggestions for this problem? Thanks

**Comment by cogaplex-bts** [comment]
We usually see the error when we compile bts without -D_GLIBCXX_USE_CXX11_ABI=0 or gcc version is lower than 5.

**Comment by HongxingGao** [comment]
I met the similar run-time error. The version of my gcc compiler was 4.8.5.  After I update the gcc version to 6.3, everything works perfect! I think the reason that GCC 4.8.5 gives error is that it doesn't support C++11 features.

**Comment by shuluoshu** [comment]
> We usually see the error when we compile bts without -D_GLIBCXX_USE_CXX11_ABI=0 or gcc version is lower than 5.

I met the same problem, i am using tensorflow 1.0 + cuda8.0,  and I tested two methods:

**Comment by cogaplex-bts** [comment]
@shuluoshu You should use  -D_GLIBCXX_USE_CXX11_ABI=0 with gcc >= 5.

**Comment by 4bitadder** [comment]
@cogaplex-bts Thanks. I succeed in compiling with conda environment by

gcc=6.3.0
tensorflow=1.13.1
cuda=10.0
cmake with -D_GLIBCXX_USE_CXX11_ABI=0
