### ISSUE TITLE
Loss on raw depth from sensor

### ISSUE THREAD

**Issue by progwiz** [cogaplex-bts/bts#113]
Hello,

I am trying to train the model on my own dataset. Raw depth data from the sensor typically has many zero valued pixels in it (around occlusions etc.). Can you tell us how you calculate the loss for such pixels, are they ignored in the provided implementation?

**Comment by cogaplex-bts** [comment]
@progwiz You are right. In our implementation, loss is defined only for pixels that have depth values.

**Comment by progwiz** [comment]
Thank you
