### ISSUE TITLE
can't download the bts_nyu.zip

### ISSUE THREAD

**Issue by lilinghui111** [cogaplex-bts/bts#12]
Hello, 
Thanks for your work!But I have some problems when I download the bts_nyu.zip, use your script download_from_gdrive.py。the error is that:

python utils/download_from_gdrive.py 1ipme-fkV4pIx87sOs31R9CD_Qg-85__h models/bts_nyu.zip

Traceback (most recent call last):
  File "utils/download_from_gdrive.py", line 45, in <module>
    download_file_from_google_drive(file_id, destination)
  File "utils/download_from_gdrive.py", line 26, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required ( Forefront TMG \xe9\x9c\x80\xe8\xa6\x81\xe6\x8e\x88\xe6\x9d\x83\xe6\x89\x8d\xe8\x83\xbd\xe5\xae\x8c\xe6\x88\x90\xe8\xaf\xb7\xe6\xb1\x82\xe3\x80\x82\xe6\x8b\x92\xe7\xbb\x9d\xe8\xae\xbf\xe9\x97\xae Web \xe4\xbb\xa3\xe7\x90\x86\xe7\xad\x9b\xe9\x80\x89\xe5\x99\xa8\xe3\x80\x82  )',)))

I am looking forward to your reply！

**Comment by lilinghui111** [comment]
I have solved the problem

**Comment by meilanyin** [comment]
@lilinghui111 hello, how did you solve the problem? I got the same issue when downloading the files.

**Comment by BillionsRichard** [comment]
how can you solved please?thank u
======================================
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1KgLFgZa9U4X7Kq1_U908idFo_GBfu04d (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5bd2def9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
python-BaseException
