### ISSUE TITLE
Some problems about local planar guidance layer

### ISSUE THREAD

**Issue by HencyChen** [cogaplex-bts/bts#14]
Dear author, 

Thanks for the wonderful works, here I would like to ask 2 questions about the proposed LPG layer:
1.   Figure 4 in the paper, the size of the feature map is H/k before Planar Guidance, and under my understanding, the Planar Guidance operation is corresponded to Eq(1), which just fuse four planes into a 1-channel maps without upsample the size of the input. But the output size of Planar Guidance in Figure 4 becomes to H, so I'm wondering if there's a bilinear operation in Planar Guidance?

2.  From the picture I highlighted, it says there's a "scaling factor" after the sigmoid layer. For my understanding, it means that n4 will multiply this factor before concatenation, but from the code it seems it didn't do that way, so I'm wondering if there is something I misunderstood.

Thank you

**Comment by cogaplex-bts** [comment]
Hello,
Thanks for your interest in our work.
1. In the LPG layer having an H/k input, each spatial location estimates kxk locally-defined relative depth using n.
2. In the function custom_sigmoid, n4 is multiplied by args.max_depth.
Thanks.

**Comment by HencyChen** [comment]
Thanks for your replies!
