### ISSUE TITLE
Testing on any single image or video 

### ISSUE THREAD

**Issue by amrbenattia** [cogaplex-bts/bts#17]
Thanks for great work. 
I am wondering, How to test on any image or video 
thanks in advance
Regards

**Comment by cogaplex-bts** [comment]
Thanks for your interest in our work.
You can use bts_sequence.py for your purpose.
We also plan to update our code to contain some c++ implementations to directly use inputs from a camera.

**Comment by muk3250** [comment]
Hello. 
@amrbenattia You managed to run the model or any image or video frames? 

I am tried to find depth on a random image of size 480x680 but I got the following error 

ValueError: Dimension 2 in both shapes must be equal, but are 84 and 85. Shapes are [1,60,84] and [1,60,85]. for 'model/decoder/concat_1' (op: 'ConcatV2') with input shapes: [1,60,84,256], [1,60,85,192], [] and with computed input tensors: input[2] = <3>.

I used the following command: 

python bts_test.py --model_name bts_nyu_v2 --dataset nyu --image_path /home/ubuntu/BTS_Test/ --out_path /home/ubuntu/BTS_Test/ --checkpoint_path ./models/bts_nyu_v2/model --input_height 480 --input_width 680

@cogaplex-bts Any suggestions what I am doing wrong here? 

Thanks in advance.

**Comment by cogaplex-bts** [comment]
@muk3250 It seems that your image is not in the shape of 480x640. If you want to test with custom sized images, make sure that they can divided by 32 with integer quotient.

**Comment by muk3250** [comment]
@cogaplex-bts Thanks for your reply. I ensured the image size to be divided by 32, but I am still unable to run it on any customized image. Now, I am getting this error 
Traceback (most recent call last):
  File "bts_sequence.py", line 184, in <module>
    tf.app.run()
  File "/home/ubuntu/BTS_Env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bts_sequence.py", line 181, in main
    test_sequence(params)
  File "bts_sequence.py", line 95, in test_sequence
    train_saver = tf.train.Saver()
  File "/home/ubuntu/BTS_Env/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/ubuntu/BTS_Env/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ubuntu/BTS_Env/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1318, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

P.S: I haven't faced any such issue for training and testing of NYU and KITTI dataset. I want to check the performance of BTS on my test images as the depth range is little bit different from NYU and KITTI.

**Comment by muk3250** [comment]
Thanks for your reply and suggestion. 
I resolved the problem. It sound strange but I just copied the sess.run file from bts_test.py and added 'feed_dict={image: input_images}' as last argument and it worked. 
May I ask until when the PyTorch version of the code will be available? 
Thanks again!
