### ISSUE TITLE
Could you please share the densenet121 pretrained model ?

### ISSUE THREAD

**Issue by huangxGo** [cogaplex-bts/bts#18]
Thanks for this nice work! 
I notice that there is a light-weight backbone densenet121 in your code, could you please share the pretrained model? Or just tell me where to download this pretrained model or checkpoint?
Regards!

**Comment by cogaplex-bts** [comment]
@huangxGo Sorry for this late reply. In the near future we will upload the requested densenet121 pretrained model to our public google drive.

**Comment by huangxGo** [comment]
> @huangxGo Sorry for this late reply. In the near future we will upload the requested densenet121 pretrained model to our public google drive.

Thank you !
