### ISSUE TITLE
Some difference with paper.

### ISSUE THREAD

**Issue by LCJHust** [cogaplex-bts/bts#19]
Hi, 
    It seems that the codes you released have some difference with the network in paper. For example,  in Figture 2, only the 1/2, 1/4 1/8 size of origin input shape have been used, but in code https://github.com/cogaplex-bts/bts/blob/master/bts.py#L241 1/16 features have been used too. Did you do some other experiments to compare the network in code and paper? Thank you.

**Comment by cogaplex-bts** [comment]
We treat 8/H iconv4 https://github.com/cogaplex-bts/bts/blob/master/bts.py#L252 as the dense features in the paper.
