### ISSUE TITLE
How generalizable is this code to other scenes?

### ISSUE THREAD

**Issue by EphChem** [cogaplex-bts/bts#20]
Thank you for releasing this code.  

As other issues have asked, I know this can be trained on nyu and kitti however when applying on a different scene, can this algorithm still perform well?  

Issue #15 is having this problem as well where they are applying your code on other scenes and are getting bad depth prediction...

Is it as easy as providing the correct focal length in "eigen_train_files_with_gt.txt" and code will provide good depth estimation for other scenes?

**Comment by cogaplex-bts** [comment]
Well, I think it is a common challenge to CNN-based architectures.
I believe if you have sufficient dataset which contains proper distribution for your testing scenes, it will work as well as it does for NYU or KITTI dataset.
Focal length is a parameter which can be obtained by intrinsic calibration.
