### ISSUE TITLE
ONNX?

### ISSUE THREAD

**Issue by MACILLAS** [cogaplex-bts/bts#25]
Hi BTS Team, 

Could you help me convert the Eigen model to ONNX format?

Many Thanks!

**Comment by cogaplex-bts** [comment]
@MACILLAS We are sorry but none of our team have experienced with ONNX. I think you can try this: https://github.com/onnx/tensorflow-onnx

**Comment by MACILLAS** [comment]
@cogaplex-bts Thanks for you response. I tried the tf2onnx library but we could not make it work for some reason... 
We really wanted to deploy this model on our custom hardware, perhaps we will try converting to TF2 and use TensorRT?
