### ISSUE TITLE
custom_layer

### ISSUE THREAD

**Issue by animareversed** [cogaplex-bts/bts#26]
Hi,
is it possible to use the custom layer in pytorch (with a new cmake) or implement it from scratch?
Thanks

**Comment by cogaplex-bts** [comment]
@animareversed We are currently working on pytorch implementation of BTS. It will be updated to this repository in the near future.

**Comment by saeid-h** [comment]
Here is a suggestion for pure tensorflow withou c code: 

[https://github.com/saeid-h/bts-fully-tf](https://github.com/saeid-h/bts-fully-tf)

**Comment by animareversed** [comment]
Oh perfect! Thank you, by any chance do you know more or less if it is going to be available before the end of January?

**Comment by cogaplex-bts** [comment]
@animareversed We plan within this month =)

**Comment by animareversed** [comment]
Great! Thank you so much :)

**Comment by Navhkrin** [comment]
I have made PyTorch implementation of BTS, you can find it under following link
https://github.com/Navhkrin/Bts-PyTorch
