### ISSUE TITLE
Random noise during training phase

### ISSUE THREAD

**Issue by Navhkrin** [cogaplex-bts/bts#27]
Greetings,

I have made PyTorch implementation of this paper, and during training phase, some of the predictions have this weird noise, i was wondering if you guys experienced something similar to this?
![image](https://user-images.githubusercontent.com/17107724/70452824-d058b300-1ab8-11ea-9059-2d9f6ba7a8bc.png)

This noise isnt present in all predictions, some of them seem normal
![image](https://user-images.githubusercontent.com/17107724/70452871-e1092900-1ab8-11ea-948c-dd2dbbcb8ce6.png)

**Comment by cogaplex-bts** [comment]
@Navhkrin Well, it seems like an issue related to tile and repeat. In our early stage of this work, we suffered similar problem with the local planar guidance layer implemented using python functions in wrong ways.
Below is our latest python implementation of the LPG layer. I think you can modify it for your pytorch implementation. Cheers =) 

    def local_planar_guidance(self, plane_eq, upratio):
        n1 = plane_eq[:, :, :, 0]
        n1 = self.tf_repeat(n1, [1, upratio, upratio])
        n2 = plane_eq[:, :, :, 1]
        n2 = self.tf_repeat(n2, [1, upratio, upratio])
        n3 = plane_eq[:, :, :, 2]
        n3 = self.tf_repeat(n3, [1, upratio, upratio])
        n4 = plane_eq[:, :, :, 3]
        n4 = self.tf_repeat(n4, [1, upratio, upratio])
        u = tf.range(upratio, dtype=tf.float32)
        u = tf.reshape(u, [1, 1, upratio])
        u = tf.tile(u, [tf.shape(plane_eq)[0], tf.shape(plane_eq)[1] * upratio, tf.shape(plane_eq)[2]])
        u = (u - tf.cast(upratio - 1, tf.float32) * 0.5) / tf.cast(upratio, tf.float32)
        v = tf.range(upratio, dtype=tf.float32)
        v = tf.reshape(v, [1, upratio, 1])
        v = tf.tile(v, [tf.shape(plane_eq)[0], tf.shape(plane_eq)[1], tf.shape(plane_eq)[2] * upratio])
        v = (v - tf.cast(upratio - 1, tf.float32) * 0.5) / tf.cast(upratio, tf.float32)
        
        return n4 / (n1*u + n2*v + n3)

**Comment by saeid-h** [comment]
How about [this for TF](https://github.com/saeid-h/bts-fully-tf/blob/master/bts.py#L131):

```
def compute_depth(self, plane_eq, upratio):
		plane = tf.concat([plane_eq]*upratio, axis=1)
		plane = tf.concat([plane]*upratio, axis=2)
		plane_normal = tf.nn.l2_normalize(plane[:, :, :, 0:3], axis=3)
		plane_dist = plane[:, :, :, 3:4]
		plane_eq = tf.concat([plane_normal, plane_dist], 3)
		pixel_vector = self.get_pixel_normalized(upratio)
		dem = tf.reduce_sum(plane_normal*pixel_vector, axis=3, keepdims=True)
		depth = plane_dist / dem * tf.sqrt(tf.reduce_sum(pixel_vector**2, axis=3, keepdims=True))
		return plane_eq, depth
	
def find_uv(self):
		h = self.params.height
		w = self.params.width
		self.u, self.v = tf.meshgrid(np.linspace(0, w-1, w, dtype=np.float32), np.linspace(0, h-1, h, dtype=np.float32)) 

	def get_pixel_normalized(self, ratio):
		if not ratio in self.pixel_normalized.keys():
			u = (self.u % ratio - (ratio - 1)/2) / self.focal
			v = (self.v % ratio - (ratio - 1)/2) / self.focal
			u = tf.expand_dims(tf.expand_dims(u, -1), 0) 
			v = tf.expand_dims(tf.expand_dims(v, -1), 0) 
			self.pixel_normalized.update({ratio: tf.concat([u, v, tf.ones_like(u)], 3)})
		return self.pixel_normalized[ratio]
```

**Comment by cogaplex-bts** [comment]
@saeid-h Thanks for the suggestion. We will consider your code in our implementation in the near future. Thanks =)

**Comment by Navhkrin** [comment]
I solved the problem, it was related to linear resizing in dataloader pipeline that i forgot to remove for some reason, outputs seem pretty clean now, thank you for the aid.

I will release the codes on github whence the model finishes training.
