### ISSUE TITLE
Inconsistency in paper and code

### ISSUE THREAD

**Issue by itsyashkothari** [cogaplex-bts/bts#3]
in bts.py
```python
concat4_daspp = tf.concat([iconv4, daspp_3, daspp_6, daspp_12, daspp_18, daspp_24], 3) 
daspp_feat = conv(concat4_daspp, num_filters / 2, 3, 1)  
...  
upconv3 = upconv(daspp_feat, num_filters, 3, 2)  # H/4
```

Here input of upconv3 is daspp_feat which is after convolution. In paper in figure 2, input of upconv3 is before convolution which is  concat4_daspp. Am I misunderstanding something ? 
![image](https://user-images.githubusercontent.com/22950744/63939803-bf45e200-ca85-11e9-8945-7eef163a6fbe.png)

**Comment by cogaplex-bts** [comment]
We meant by "ASPP" module to include a convolution with an input of concatenated feature maps from dilated sparse convolutions.
Because the ASPP is not our own idea, we briefly mentioned about it.
The same structure can be found from [47].
Thanks =)

**Comment by itsyashkothari** [comment]
Code uses output of ASPP, which is daspp_feat as input of Local Planer guidance 
```python 
rconv1_8x8 = self.reduction_1x1(daspp_feat, num_filters / 2)
```

Shouldn't there be one more layer of convolution before passing to lpg8x8 as mentioned in paper?

**Comment by cogaplex-bts** [comment]
Oh... You are right.
The input to the first upconv should be came from the first conv.
We will update the figure.
Thanks for pointing this.
