### ISSUE TITLE
Questions about LPG

### ISSUE THREAD

**Issue by wanghaijie2017** [cogaplex-bts/bts#35]
According to my understanding, n1, n2, n3 in the following formula represent the unit normal vector of the local plane of k x k size, and n4 represents the distance. And the purpose of this formula is to calculate the depth of each pixel of the local area of ​​k x k size.

  > d = n4 / (n1\*u + n2\*v + n3)

I am curious about how this formula is obtained.

**Comment by cogaplex-bts** [comment]
@wanghaijie2017 They are derived from well known equation for 'ray-plane intersection' https://www.cs.princeton.edu/courses/archive/fall00/cs426/lectures/raycast/sld017.htm
where V: (u, v, 1), N: (n1, n2, n3), d: n4 and P0: (0, 0, 0) in this work.

**Comment by wanghaijie2017** [comment]
thanks for your helpful reply.

**Comment by suyuzhang** [comment]
`
theta = self.sigmoid(net[:, 0, :, :]) * math.pi / 3
`
`
phi = self.sigmoid(net[:, 1, :, :]) * math.pi * 2
`
@cogaplex-bts  I am also curious about how this formula is obtained.
