### ISSUE TITLE
missing resnet_v1

### ISSUE THREAD

**Issue by derekwong66** [cogaplex-bts/bts#38]
Hello,

Thanks for ur sharing this code. I am currently trying the tensorflow version. I have downloaded models under tensorflow folder. Then I run python bts_test.py arguments_test_eigen.txt.
error shows that:
Traceback (most recent call last):
  File "bts_test.py", line 66, in <module>
    for key, val in vars(__import__(args.model_name)).items():
  File "./models/bts_eigen_v2/bts_eigen_v2.py", line 25, in <module>
    from resnet_v1 import *
ImportError: No module named resnet_v1

**Comment by derekwong66** [comment]
btw, I was trying densenet161_bts

**Comment by cogaplex-bts** [comment]
@derekwong66 Sorry for the inconvenience. Just remove the line 
from resnet_v1 import *
and try again.

**Comment by derekwong66** [comment]
It works! densenet161 takes around 2.2s/it. It is far slow than its result published at KITTI web(~ 0.1s).
My working environment is GTX1080 cuda10.0 tensorflow1.13.2

**Comment by cogaplex-bts** [comment]
@derekwong66 In that case, you may run the code without cuda support. You can check whether your system is using cuda with 'nvidia-smi' while the code is running.

**Comment by derekwong66** [comment]
It's my problem. Right now, the code can run at around 8.30 it/s. Thanks for ur effort.
