### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by Fangyh09** [cogaplex-bts/bts#4]
Hello,
I followed these commands, but 'bathroom_0039', 'living_room_0019', 'living_room_0018', 'bedroom_0076a', 'living_room_0020' are missing.
```
$ cd ~/workspace/dataset/nyu_depth_v2
$ mkdir raw && cd raw
$ aria2c -x 16 -i ../../bts/utils/nyudepthv2_archives_to_download.txt
$ parallel unzip ::: *.zip
```

**Comment by cogaplex-bts** [comment]
Hello,
Sorry for the incomplete instruction.
I remember that there was an issue with the directory names and I had to change them manullay to correspond with scene names defined in "nyu_depth_v2_labeled.mat".

Temporarily, you can download our training set using following command.
```
$ python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP ../dataset/nyu_depth_v2/sync.zip
```

**Comment by cogaplex-bts** [comment]
It seems that there are some changes in the dataset.
If we see contents in "rawRgbFilenames" in "nyu_depth_v2_labeled.mat", there are entries pointing the missing directories but the raw files seem removed.
Temporarily, you can download our training set using following command.
```
$ python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP ../dataset/nyu_depth_v2/sync.zip
```

**Comment by Fangyh09** [comment]
@cogaplex-bts 
Would you please provide the testing images as well?

**Comment by cogaplex-bts** [comment]
You can get testing images through instruction in readme.

**Comment by rk800506** [comment]
> 
> 
> It seems that there are some changes in the dataset.
> If we see contents in "rawRgbFilenames" in "nyu_depth_v2_labeled.mat", there are entries pointing the missing directories but the raw files seem removed.
> Temporarily, you can download our training set using following command.
> 
> ```
> $ python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP ../dataset/nyu_depth_v2/sync.zip
> ```

I was able to download the dataset till tommorow, but it does not download anything since today. The returned **token** in the **download_from_gdrive** returns **None**.

Is the file removed form google drive?

**Comment by LeiyuanMa** [comment]
> It seems that there are some changes in the dataset. If we see contents in "rawRgbFilenames" in "nyu_depth_v2_labeled.mat", there are entries pointing the missing directories but the raw files seem removed. Temporarily, you can download our training set using following command.
> 
> ```
> $ python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP ../dataset/nyu_depth_v2/sync.zip
> ```

This code seems not working anymore, the returned token in the download_from_gdrive returns None. However I tried to download  this dataset using  wget the code I am using is listed below, but **some folders was lost**, 240 folders, although the zip file is 5.9G in linux.
‘’‘
#!/bin/bash
if [ $# != 2 ]; then
echo "Usage: googledown.sh ID save_name"
exit 0
fi
confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='$1 -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
echo $confirm
wget -c -t 0 --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$confirm&id=$1" -O $2 && rm -rf /tmp/cookies.txt
’‘’

So I tried download using chrome browser, the downloaded zip file is 6.35G in Mac, 6.0G in linux, both 284 folders,  44 folders was lost using aforementioned method, so it's quiet confusing. I think it's better to attach a md5 of this file in README.md, so anyone who wants to follow your work will able to check the completeness of the data.

**Comment by cleinc** [comment]
@LeiyuanMa Can you try following link?:
https://drive.google.com/file/d/1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP/view?usp=sharing

**Comment by LeiyuanMa** [comment]
> @LeiyuanMa Can you try following link?: https://drive.google.com/file/d/1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP/view?usp=sharing

”https://drive.google.com/u/0/uc?id=1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP&export=download“
“https://drive.google.com/uc?id=1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP&export=download”
this two links seems quiet similar to each other, but I'll try after the download is finished, anyway, attach a md5 of file is highly recommended,such as [https://www.cs.stanford.edu/~roozbeh/pascal-context/](url)
