### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Fangyh09** [cogaplex-bts/bts#5]
Hello,
I follow instructions in the readme, but I got segmentation fault. My python version is 2.7
```
segmentation fault (core dumped)  python bts_main.py arguments_train_nyu.txt
```

**Comment by cogaplex-bts** [comment]
Well, do you use tensorflow built from source?
If not, please build tf.
We noticed that tensorflow installed using binary package causes segfault and trying to fix it.
Sorry for the inconvenience.

**Comment by Fangyh09** [comment]
I use pip to install it.

**Comment by Fangyh09** [comment]
Could you provide a docker image?

**Comment by cogaplex-bts** [comment]
Sorry, we are not using docker.

**Comment by Fangyh09** [comment]
I find one, `docker pull tensorflow/tensorflow:1.14.0-gpu-py3`

**Comment by cogaplex-bts** [comment]
Is it working well with bts?

**Comment by Fangyh09** [comment]
Nope.

**Comment by Fangyh09** [comment]
Which python do you use? python2.7 or python3.6?

**Comment by cogaplex-bts** [comment]
We tested with both of 2.7 and 3.6.

**Comment by Fangyh09** [comment]
Would you please upload the built whl file?

**Comment by cogaplex-bts** [comment]
We have just checked with a pip installed tensorflow-gpu==1.13.2, it works well with bts.
So you can try with following command:
```
$ pip install tensorflow-gpu==1.13.2
```

**Comment by frankcarey** [comment]
FYI: I created a Dockerfile for this here: 
https://github.com/cogaplex-bts/bts/pull/7

**Comment by EphChem** [comment]
I have tried tensorflow-gpu==1.13.2 with python 3.6 but I get following gpu_kernel_helper.h not found error, see below:
```
fatal error: tensorflow/core/util/gpu_kernel_helper.h: No such file or directory
 #include "tensorflow/core/util/gpu_kernel_helper.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at compute_depth_generated_compute_depth.cu.o.cmake:215 (message):
  Error generating
  /<path>/bts-master/custom_layer/build/CMakeFiles/compute_depth.dir//./compute_depth_generated_compute_depth.cu.o
```

I have also tried tensorflow-gpu==1.14.0 with python 3.6 and I also get segmentation fault
