### ISSUE TITLE
Incorrect NYU cropping caused by Indexing issue

### ISSUE THREAD

**Issue by jungerm2** [cogaplex-bts/bts#61]
In `get_projection_mask.m` from the original nyuv2 toolkit, the mask is defined by:
```
mask = false(480, 640);
mask(45:471, 41:601) = 1;
```
Since Matlab indices start at 1 and are inclusive, the numpy equivalent should be [44:471, 40:601] instead. This is used here:
https://github.com/cogaplex-bts/bts/blob/e63ccc00a1d44cc417c745714e3cabe58559f054/utils/eval_with_pngs.py#L205

**Comment by cogaplex-bts** [comment]
@jungerm2 Thanks for correcting us! We will update our code as well as the results.

**Comment by jungerm2** [comment]
I was also wondering why you didn't provide any accuracy metrics with smaller thresholds, I know that the 1.25^i is the standard one, but the results are so good you could've benefited from smaller deltas. Did you consider this? Thanks!
