### ISSUE TITLE
Inconsistent memory usage during model initialization

### ISSUE THREAD

**Issue by kHarshit** [cogaplex-bts/bts#62]
Hi,

During model initialization, memory usage is inconsistently fluctuating. But when the training starts, it gets stable. What could be the cause of that?

**Comment by cogaplex-bts** [comment]
@kHarshit Well, we have no idea about it, but only guessing it is related to graph construction by PyTorch when training starts.

**Comment by kHarshit** [comment]
Okay, Thanks
