### ISSUE TITLE
Number of training samples from Drive different from that in paper

### ISSUE THREAD

**Issue by zergzzlun** [cogaplex-bts/bts#79]
Hi, thank you for open-sourcing your wonderful work.

After downloading the NYUDv2 dataset from Google Drive following your instructions, I found that there're totally 36396 samples in the downloaded file, i.e. sync.zip, which is different from 24231 described in the paper. Why is this?

Many thanks.

**Comment by ShenZheng2000** [comment]
@zergzzlun Have you find the solution?
