### ISSUE TITLE
Artifacts in upper part of KITTI images only in Pytorch model

### ISSUE THREAD

**Issue by pjckoch** [cogaplex-bts/bts#91]
Hi, 

I have tried out both the TF and PyTorch implementation with your pre-trained models.

I noticed that the artifacts in the upper part of the image, which are also mentioned in section 4.7 of your paper, only appear in the PyTorch version. The TF version does not seem to be affected. 

Do you have any idea where this difference could come from? Did you use different parameters for training the PyTorch version?

Thanks in advance! See below for an example.

### PyTorch:
2011_09_26_drive_0013_sync_0000000050.png
![PyTorch_2011_09_26_drive_0013_sync_0000000050](https://user-images.githubusercontent.com/38760750/97899839-173b4100-1d3a-11eb-8a4a-2a03db3e43f2.png)

### TF:
2011_09_26_drive_0013_sync_0000000050.png
![TF_2011_09_26_drive_0013_sync_0000000050](https://user-images.githubusercontent.com/38760750/97899848-1c988b80-1d3a-11eb-9d88-0d2e2530a6b0.png)

**Comment by cogaplex-bts** [comment]
@pjckoch Sorry for this late reply. As you may know, most of the ground truth depthmaps lack valid depth values on upper part on the images and this leads to the random behaviour on our network.
