### ISSUE TITLE
pytorch/bts.py Encoder 관련 질문입니다.

### ISSUE THREAD

**Issue by Taeyoung96** [cogaplex-bts/bts#98]
안녕하세요.  
좋은 연구와 코드까지 공개해 주셔서 너무 감사드립니다.  
논문을 읽어보고 코드를 보며 궁금한 점이 있어 이렇게 Issue를 남기게 되었습니다.  

<p align="center"><img src="https://user-images.githubusercontent.com/41863759/102438859-7510b780-4060-11eb-8676-f96a777b8a2a.png" width = "500" ></p>  

논문에는 'Table 5'에 base network를 'MobileNetV2'를 이용하여 실험한 결과가 나와있는데,  
공개해주신 코드에는 Backbone network에 'MobileNetV2'에 대한 정보가 없어 직접 구현을 하려고 합니다.  

공개해주신 코드의 `pytorch/bts.py`에 `class encoder()` 부분을 보면,  
여러 pretrained model을 선택할 수 있도록 되어 있습니다.  

여기 mobilenet network를 추가하고 싶은데,  
network마다 out_put_channels의 갯수가 달라 어떤식으로 구현을 해야하는지 궁금합니다.  
(제가 아직 지식이 부족하다보니... 이런 질문을 하게 되네요 :cry:)  

```python
elif params.encoder == 'mobilenet_v2_bts':
    self.base_model = models.mobilenet_v2(pretrained=True)
    self.feat_names = ['relu', 'layer1', 'layer2', 'layer3', 'layer4']
    self.feat_out_channels = [64, 256, 512, 1024, 2048]
```
이렇게 추가를 하고 Training을 돌리면 될까요?  
아님 output channels를 다르게 해주어야 할까요?  

답변해주시면 감사드리겠습니다.

**Comment by cogaplex-bts** [comment]
@Taeyoung96 안녕하세요. 제가 mobilenetv2 옵션을 업데이트하는걸 깜빡했었네요. 새로 커밋했으니 확인해보세요. 감사합니다. =)

**Comment by Taeyoung96** [comment]
@cogaplex-bts 확인했습니다! 빠른 답변 및 수정 감사드립니다. 😄
